New branch SOAP project
DipDeepCode/KTE_Labs-test-task pull request #3
Opened 2023-10-14 19:31 UTC by albinavita

К проекту добавлены методы CRUD и валидация

2023-10-15 08:30 UTC, DipDeepCode requested changes
Есть замечания. Необходимо внести изменения.

2023-10-15 08:30 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/server/CountryService.java
> +        }
Такая обработка исключения не нужна. В дальнейшем мы напишем отдельный класс для обработки исключений.

2023-10-15 08:30 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/server/CountryService.java
> +    }
Такая обработка исключения не нужна. В дальнейшем мы напишем отдельный класс для обработки исключений.

2023-10-15 08:30 UTC, DipDeepCode commented on src/main/resources/countries.xsd
> +  <xs:element name="deleteCountryRequestByName">
Здесь просится название deleteCountryByNameRequest

2023-10-15 08:30 UTC, DipDeepCode commented on src/main/resources/countries.xsd
> +  <xs:element name="deleteCountryRequest">
Здесь просится название deleteCountryByIdRequest

2023-10-15 08:52 UTC, albinavita commented on pom.xml
> +		</dependency>
> После изменения валидации эта зависимость уже не нужна. Кроме того эту зависимость можно использовать когда используется чистый hibernate. А этот проект основан на spring boot, и надо использовать зависимость spring-boot-starter-validation. Она нам понадобится позже, когда будем реализовывать REST.

Спасибо, убрала

2023-10-15 08:57 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +    public AddCountryResponse getName(@RequestPayload AddCountryRequest request) {
Изменила

2023-10-15 08:58 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +    public DeleteCountryResponse deleteCountry(@RequestPayload DeleteCountryRequest request) {
Переименовала

2023-10-15 09:00 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +        }
Питалась обновить enum. Забыла убрать

2023-10-15 09:38 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/server/CountryService.java
> +        }
> Такая обработка исключения не нужна. В дальнейшем мы напишем отдельный класс для обработки исключений.

Удалила

2023-10-15 09:38 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/server/CountryService.java
> +    }
Удалила

2023-10-15 09:40 UTC, albinavita commented on src/main/resources/countries.xsd
> +  <xs:element name="deleteCountryRequestByName">
Изменила

2023-10-15 09:40 UTC, albinavita commented on src/main/resources/countries.xsd
> +  <xs:element name="deleteCountryRequest">
Изменила

2023-10-15 09:41 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/repository/CountryRepository.java
> +    Optional<CountryEntity> deleteByName(String name);
Установила, но пока не пойму как пользоваться

2023-10-15 18:02 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +    public UpdateCountryResponse updateCountryResponse(@RequestPayload UpdateCountryRequest request) {
Почему не соответствует? Ведь мы не знаем какой из параметров будет изменен

2023-10-15 18:05 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/models/CountryEntity.java
> +    }
Для сравнения объектов. В будущем вполне возможно будут сравниваться объекты?

2023-10-19 08:20 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +        }
До сих пор не убрана эта часть кода

2023-10-19 08:24 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +    public UpdateCountryResponse updateCountryResponse(@RequestPayload UpdateCountryRequest request) {
А зачем нам знать какой параметр будет изменен?
Читая название метода я прихожу к выводу что будет изменяться CountryResponse, но заглядывая внутрь метода, я вижу что изменяется Country. Должно быть updateCountry.

2023-10-19 08:30 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/models/CountryEntity.java
> +    }
Когда надо будет сравнивать, тогда и надо добавлять эти методы.
Дело в том, что надо сначала понять по каким параметрам сравнивать.
Сейчас у вас в эти методы добавлены все поля сущности. 
Исходя из этого получается что может быть две страны:
Первая: Spain, Madrid, EUR, 46704314
Вторая: Spain, Madrid, EUR, 46704313
И это будут разные страны!!!

2023-10-19 08:31 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/repository/CountryRepository.java
> +    Optional<CountryEntity> deleteByName(String name);
Поищите на youtube, там много примеров как пользоваться от авторов плагина

2023-10-19 18:38 UTC, albinavita commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +        }
countryEntity.setCurrency(convertToCurrencyEnum(request.getCountry().getCurrency())); Это я удалила
Строки выше нельзя удалять, т.к. название и столица не будут меняться

2023-10-20 06:56 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/endpoint/CountryEndpoint.java
> +        }
Как это не будут? Из метода countryService.update(...) уже возвращается CountryEntity с новыми данными

2023-10-21 07:45 UTC, DipDeepCode requested changes

2023-10-21 07:45 UTC, DipDeepCode commented on src/main/java/ru/ddc/springwebservice/models/CurrencyEnum.java
> +    RUB;
Такое недопустимо! Коммит называется Deleted if in class ContryEndpoint, но в нем есть изменения в другом классе!

2023-10-21 18:01 UTC, DipDeepCode approved these changes
Отлично

2023-10-21 18:15 UTC, merged